config/routes.rb
Twactivism::Application.routes.draw do

  resources :welcome, :only => [:index]
  root :to => 'welcome#index'

  resources :tweets, :only => [:create, :new]
  resources :shit_lists, :only => [:create]

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

end

app/models/politician.rb
class Politician < ActiveRecord::Base
  attr_accessible :handle, :name, :party, :state, :avatar
  has_many :tweets
  
  has_many :shit_list_politicians
  has_many :shit_lists, :through => :shit_list_politicians
end

app/models/shit_list.rb
class ShitList < ActiveRecord::Base
  attr_accessible :about, :avatar, :title, :politicians, :more
  has_many :shit_list_politicians
  has_many :politicians, :through => :shit_list_politicians

  def self.create_from_params(params)
    politicians = Politician.find(params['ids'])
    title = params['title']
    about = params['about']
    more  = params['more']
    ShitList.create(:about => about, :more => more, :title => title, :politicians => politicians)
  end

  def politician_ids
    politicians.map(&:id).join(",")
  end
end

app/models/shit_list_politician.rb
class ShitListPolitician < ActiveRecord::Base
  attr_accessible :politician_id, :shit_list_id

  belongs_to :politician
  belongs_to :shit_list

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  attr_accessible :user_id, :recipient, :sent_at, :content, :politician_id

  belongs_to :user
  belongs_to :politician

  after_create :transmit

  def transmit
    Thread.new{user.twitter_client.update(written_tweet)}
    update_attribute(:sent_at, DateTime.now)
  end

private

  def written_tweet
    content.gsub("<<recipient>>", recipient)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tweets

  def self.from_omniauth(auth)
    where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["nickname"]
      user.image = auth["info"]["image"]
      user.token = auth["credentials"]["token"]
      user.secret = auth["credentials"]["secret"]
    end
  end

  def twitter_client
    Twitter::Client.new(
      :oauth_token => token,
      :oauth_token_secret => secret
    )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :verify_authenticity_token, :only => :create

  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end
end

app/controllers/shit_lists_controller.rb
class ShitListsController < ApplicationController

  def create
    @shitlist = ShitList.create_from_params(params["shit_list"])
    render :json => {title: @shitlist.title, id: @shitlist.id, poli_ids: @shitlist.politician_ids}
  end
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def create
    content = params["content"]
    politicians = Politician.find(params["poli_ids"].reject(&:empty?))

    politicians.each do |politician|
      current_user.tweets.create(:recipient => politician.handle, :content => content, :politician_id => politician.id)
    end
    render :json => {}
  end

  # def new
  #   #TODO create a tweet for each param the user sends.  this should
  #   #create a tweets for each recipient
  #   recipients = ["1","2","3"]

  #   recipients.each do |recipient|
  #     current_user.tweets.create(:recipient => recipient, :content => params['content'], :politician_id => Politician.first.id)
  #   end
    
  #   redirect_to root_path
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_filter :current_user

  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shit_lists_helper.rb
module ShitListsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Twactivism" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
    <div class="container">
        <% if @current_user %>
            <div class="navbar navbar-fixed-top">  
              <div class="navbar-inner">
                <h3 id="nav-title">tweet at politicians</h3>
                <p id="nav-login">logged in as <%= @current_user.name %>
                    <%= link_to "sign out", signout_path %>
                </p>
              </div>  
            </div>
        <% end %>
        <div class="row">
          <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/politicians/_selected_politicians.html.erb
<h3>your tweet(s) will be sent to the following recipients:</h3>
<ul id="selected-list">
</ul>

<script id="stache-selected-politician" type="text/x-mustache">
    <li id="{{id}}">{{name}}
      <img class="selected-image" src="{{image}}"/>
    </li>
</script>

app/views/shit_lists/_shit_list_form.html.erb
<p>Name your shit list:</p>
<%= text_field_tag 'title',nil, :placeholder => 'Sl name', :id => 'shitlist-title' %>

<p>Select politicians</p>
<select data-placeholder="Select Politicians for a shit list" id="shitlist-create" multiple style="width:350px;" tabindex="4">
  <% Politician.all.each do |poli| %>
    <option value="<%= poli.id %>" data-name="<%= poli.name%>"
            data-image="<%= poli.avatar %>">
      <%= poli.name %>
    </option>
  <% end %>
</select>

<p>Whats it all about?</p>
<%= text_area_tag 'about', nil, :size => "125x5", :id => "shitlist-about" %>

<p>How can people learn more?</p>
<%= text_area_tag 'more', nil, :size => "125x5", :id => "shitlist-more" %>

<button id="shitlist-submit" class="btn btn-primary btn-block">Create a Shit List!</button>

app/views/shit_lists/_shit_list_modal.html.erb
<div id="shitlist-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h2 id="myModalLabel">Create a New Shit List</h2>
  </div>
  <div class="modal-body" id="shitlist-modal-body">
    <%= render :partial => 'shit_lists/shit_list_form' %>
  </div>
</div>

app/views/shit_lists/_shit_lists.html.erb
<ul id="shit-lists">
  <% ShitList.all.each do |sl| %>
    <li>
      <a href="#" id="<%= sl.id %>" class="shit-list-link"
         data-poli-ids="<%= sl.politician_ids %>">
         <%= sl.title %>
      </a>
    </li>
  <% end %>
</ul>

<script id="stache-shitlist" type="text/x-mustache">
    <li>
      <a href="#" id="{{id}}" class="shit-list-link"
         data-poli-ids="{{poli_ids}}">
         {{title}}
      </a>
    </li>
</script>

app/views/welcome/_address.html.erb
<div class="item-inner">
  <h1>select some politicians</h1>

  <div id="chosen-holder">
    <select data-placeholder="Choose a Politician" id="politician-select" multiple style="width:350px;" tabindex="4">
        <option value=""></option>
        <%= Politician.all.each do |poli| %>
          <option class="politician-select" value="<%= poli.id %>"
                  data-id="<%= poli.id %>" data-name="<%= poli.name%>" data-image="<%= poli.avatar %>">
            <%= poli.name %>
          </option>
        <% end %>
    </select>
  </div>

  <div id="options-holder">
    <ul id="options">
      <li>
        a.  select from the above list
      </li>

      <li>
        b. select from a precompiled shit list
        <%= render :partial => "shit_lists/shit_lists" %>
      </li>

      <li>
        <a href="#shitlist-modal" role="button" class="btn btn-success" data-toggle="modal">create a new shit list</a>
        <%= render :partial => 'shit_lists/shit_list_modal' %>
      </li>

    </ul>
  </div>


  <%= link_to "compose your tweet","#", :id => "compose-button", :class => "btn btn-large btn-block btn-primary" %>
</div>

app/views/welcome/_compose.html.erb
<div class="item-inner">
  <%= link_to "return to select other politicians", "#", :id => "return-address" %>
  <h1>compose your tweet(s)</h1>

  <div id="compose-holder">
    <%= text_field_tag 'tweet-content', nil, :placeholder => 'Compose your tweet...', :size => 60 %>
    <p>include << recipient >> where you'd like the politicians twitter handle in your message </p>
  </div>

  <%= render :partial => "politicians/selected_politicians" %>

  <%= link_to "send your tweets","#", :id => "submit-button", :class => "btn btn-large btn-block btn-primary" %>
</div>

app/views/welcome/_landing.html.erb
<div id="landing-container">
  <div id="login-container">
    <a href="/auth/twitter">
      <button id="login-button" class="btn btn-large btn-block btn-primary" type="button">
        Sign-in With Twitter To Get Started
      </button>
    </a>
  </div>
</div>

app/views/welcome/_share.html.erb
<div class="item-inner">
  <h2> This is the share screen</h2>
</div>

app/views/welcome/index.html.erb
<% if @current_user %>
<div id="carousel-container">
  <ul id="user-status">
    <li id="address" class="active">address</li>
    <li id="compose">compose</li>
    <li id="share">share</li>
  </ul>

  <div id="myCarousel" class="carousel slide">
    <div class="carousel-inner">
      <div class="active item"><%= render :partial => 'address' %></div>
      <div class="item"><%= render :partial => 'compose' %></div>
      <div class="item"><%= render :partial => 'share' %></div>
    </div>
  </div>
</div>
  
<% else %>
  <%= render :partial => 'landing' %>
<% end %>